// =================== DO NOT EDIT THIS FILE ====================
// Generated by Modello 1.7,
// any modifications will be overwritten.
// ==============================================================

package org.apache.archiva.admin.model.beans;

import javax.xml.bind.annotation.XmlRootElement;
import java.io.Serializable;

/**
 * File Locking configuration.
 *
 * @since 2.0.0
 */
@XmlRootElement( name = "fileLockConfiguration" )
public class FileLockConfiguration
    implements Serializable
{

    /**
     * skipping the locking mechanism.
     */
    private boolean skipLocking = true;

    /**
     * maximum time to wait to get the file lock (0 infinite).
     */
    private int lockingTimeout = 0;


    /**
     * Get maximum time to wait to get the file lock (0 infinite).
     *
     * @return int
     */
    public int getLockingTimeout()
    {
        return this.lockingTimeout;
    }

    /**
     * Get skipping the locking mechanism.
     *
     * @return boolean
     */
    public boolean isSkipLocking()
    {
        return this.skipLocking;
    }

    /**
     * Set maximum time to wait to get the file lock (0 infinite).
     *
     * @param lockingTimeout
     */
    public void setLockingTimeout( int lockingTimeout )
    {
        this.lockingTimeout = lockingTimeout;
    }

    /**
     * Set skipping the locking mechanism.
     *
     * @param skipLocking
     */
    public void setSkipLocking( boolean skipLocking )
    {
        this.skipLocking = skipLocking;
    }

}
